#!/usr/bin/perl
#
# Licensed to the Apache Software Foundation (ASF) under one or or more
# contributor license agreements. See the NOTICE file distributed with this
# work for additional information regarding copyright ownership. The ASF
# licenses this file to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#

use FindBin;
use lib "$FindBin::Bin/lib";

use Mojolicious::Lite;

use Mojo::MQTT::Message;
use Mojo::UserAgent;
use Mojo::Util 'dumper';
use Time::Piece;

use constant {
  CONFIG_PATH => $ENV{BHACKD_CONFIG} // '/conf/bhackd.conf'
};

app->log->info('Configuration: ' . CONFIG_PATH);

plugin 'JSONConfig'      => {file => CONFIG_PATH};
plugin 'Plugins::Stream' => app->config->{streams} // {};

Mojo::IOLoop->recurring(5 => sub {
  app->stream->mqtt->start(on_data => sub {
    my $args = {@_};

    my $ret = app->stream->publish(
      stream   => $args->{stream},
      origin   => 'mqtt',
      data     => $args->{data},
    );

    app->log->debug('MQTT: write ' . ($ret ? 'ok' : 'nok') . '.');
  });
});

Mojo::IOLoop->start unless Mojo::IOLoop->is_running;
