version: "2"

services:
  mosquitto:
    container_name: bhack_mosquitto
    image: "bhack_mosquitto:${BUILD}"
    build:
      context: ./docker/mosquitto
    restart: always
    ports:
      - "${BHACKD_MOSQUITTO_PORT}:1883"
    volumes:
      - ./conf:/conf:ro

  website:
    container_name: bhack_website
    image: "bhack_website:${BUILD}"
    build:
      context: ./docker/website
    restart: always
    ports:
      - "${BHACKD_WEBSITE_PORT}:3000"
    environment:
      - BHACKD_CONFIG
    volumes:
      - ./conf:/conf:ro
      - ./data:/data
      - ./blog:/blog:ro

  streams:
    container_name: bhack_streams
    image: "bhack_streams:${BUILD}"
    build:
      context: ./docker/streams
    restart: always
    environment:
      - BHACKD_CONFIG
    volumes:
      - ./conf:/conf:ro
      - ./data:/data
