version: "3"

services:
  mosquitto:
    build: ./docker/mosquitto

    ports:
      - "${BHACKD_MOSQUITTO_PORT}:1883"

    volumes:
      - ./conf:/conf:ro

  website:
    build: ./docker/website

    ports:
      - "${BHACKD_WEBSITE_PORT}:3000"

    environment:
      - BHACKD_CONFIG

    volumes:
      - ./conf:/conf:ro
      - ./data:/data
      - ./blog:/blog:ro

  streams:
    build: ./docker/streams

    environment:
      - BHACKD_CONFIG

    volumes:
      - ./conf:/conf:ro
      - ./data:/data
